### ISSUE TITLE
Flat Textures

### ISSUE THREAD

**Issue by Galaxta** [KdGaming0/SkyBlock-Enhanced-Modpack#2] opened 2024-07-06 02:58 UTC
After updating to the most recent version (1.0.1), All items in my hands and in other players have become flat.
![image](https://github.com/KdGaming0/SkyBlock-Enhanced-Modpack/assets/153929948/de09dd0b-1cb7-4a74-bc00-1b3f4969245e)
![image](https://github.com/KdGaming0/SkyBlock-Enhanced-Modpack/assets/153929948/6c1d06d7-4e91-4d78-8a0a-047df999125e)
![image](https://github.com/KdGaming0/SkyBlock-Enhanced-Modpack/assets/153929948/81428f75-efc0-40ee-a7bd-6f40f76db39e)

Reloading Textures or Changing Texture packs does not fix it.

**Comment by KdGaming0** [comment] 2024-07-06 06:47
Hello, did you update from 1.0.0 or 0.1.11? If you updated from 1.0.0 did you have the problem then? 1.0 has been taken down because I by accident shipped Optifine with the modpack so when you updated from 1.0.0 to 1.0.1 optifine may have been removed and you need to download it again.

**Comment by KdGaming0** [comment] 2024-07-06 14:27
Fixed in the 1.0.2 update. It was caused by FoemFix it is a mod that is supposed to lower memory usage but it looks like it makes the textures in your hand flat also. I have removed the mod for now.

**Comment by TheBrutalSkull** [comment] 2024-07-31 18:01
I'm pretty sure the issue is caused by TexFix because it's still the case in the later version of the modpack.

**Comment by KdGaming0** [comment] 2024-07-31 19:08
> I'm pretty sure the issue is caused by TexFix because it's still the case in the later version of the modpack.

Can you show pictures. I don't have a problem after I remove fomfix. Dose the texture get fixed if you remove texfix.

**Comment by TheBrutalSkull** [comment] 2024-08-01 04:40
![Screenshot 2024-08-01 003801](https://github.com/user-attachments/assets/06ac7622-7a35-465a-9a89-42ca2a82c57f)
![Screenshot 2024-08-01 003944](https://github.com/user-attachments/assets/143df2f9-94e9-4a99-8222-540169fc52bd)

**Comment by TheBrutalSkull** [comment] 2024-08-01 04:40
First is with the mod, and second is without it

**Comment by KdGaming0** [comment] 2024-08-11 18:32
Fixed in 1.1.3 removed texfix and readded FomFix.

**Closed by KdGaming0** 2024-08-11 18:32 UTC
